---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinfra-httpd
  labels:
    app: webinfra
spec:
  selector:
    matchLabels:
      app: webinfra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webinfra
    spec:
      containers:
      - image: kevharv/httpd-enterprise:latest
        name: httpd-enterprise
        ports:
        - containerPort: 80
          name: http
        - containerPort: 81
          name: webdav
        volumeMounts:
        - name: site-data
          mountPath: /usr/local/apache2/htdocs
        - name: server-config
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
        - name: dav-lock
          mountPath: /var/lib/dav
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: webinfra-sitedata
      - name: server-config
        configMap:
          name: httpd-config
      - name: dav-lock
        persistentVolumeClaim:
          claimName: webinfra-davlock