---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webinfra-sitedata
  labels:
    app: webinfra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webinfra-davlock
  labels:
    app: webinfra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi